#configuration for makefile
#So that makefile stays largely despite the same despite the libraries being used

#High-level libraries used
#Must specify both the sub-folder levels
#and the files themselves
#	eg. HL_LIBS += blargh.c

#HL_LIBS += usbSerial.c

HL_LIBS_CPP += $(ROOT)main.cpp

SUBHIGH += -I lib
HL_LIBS_CPP += lib/protocol/drawing/drawing.cpp
HL_LIBS_CPP += lib/periph/i2c/i2cMaster.cpp
HL_LIBS_CPP += lib/devices/ssd1306/ssd1306.cpp
HL_LIBS_CPP += lib/devices/gy521/gy521.cpp


HL_LIBS_CPP += taskBlink.cpp
HL_LIBS_CPP += OledTask.cpp